export const LANDING_LB_VISIBLE_ROWS = 5

const LB_ROW_HEIGHT = 22
const LB_ROW_GAP = 2
export const LANDING_LB_TOPBAR_HEIGHT = 43
const LB_PANEL_PAD_Y = 14
const LB_FOOT_HEIGHT = 33

export const LANDING_LB_LIST_HEIGHT = LB_ROW_HEIGHT * LANDING_LB_VISIBLE_ROWS + LB_ROW_GAP * (LANDING_LB_VISIBLE_ROWS - 1)

/** Fixed shell height — keeps SSR/CSR layout stable (no CLS). */
export const LANDING_LB_SHELL_HEIGHT = LANDING_LB_TOPBAR_HEIGHT + LB_PANEL_PAD_Y + LANDING_LB_LIST_HEIGHT + LB_FOOT_HEIGHT

export const LANDING_LB_PANEL_HEIGHT = LANDING_LB_SHELL_HEIGHT - LANDING_LB_TOPBAR_HEIGHT
