import { getTileSprites } from '../ui/tile-sprites.ts';
import type { AssetLabSection } from './routes.ts';
import { audioNavItems, mountAudioPanels, type AudioPanelId } from './asset-gallery/audio-lab.ts';
import { backdropNavItems, mountBackdropPanels, type BackdropPanelId } from './asset-gallery/ambient-backdrop-lab.ts';
import {
  createFooterNote,
  createPanelHead,
  createSidebar,
  createTopbar,
  createWorkspace,
  type NavItem,
} from './asset-gallery/editor-shell.ts';
import { mountEffectPanels, type EffectPanelId } from './asset-gallery/cell-effects.ts';
import { gameUiNavItems, mountGameUiPanels, type GameUiLabPanelId } from './asset-gallery/game-ui-lab.ts';

const TILE_BASE = '/assets/tiles';
const RUNTIME_BOARD_TILE_BASE = '/assets/candidates/board-v3-square/tiles';

interface AssetItem {
  id: string;
  label: string;
  src: string;
  image: HTMLImageElement;
}

interface AssetSection {
  id: string;
  title: string;
  description: string;
  items: AssetItem[];
}

interface StaticPreviewItem {
  id: string;
  label: string;
  src: string;
  note?: string;
  background?: 'checker' | 'black' | 'dark';
}

interface StaticPreviewSection {
  id: string;
  title: string;
  description: string;
  items: StaticPreviewItem[];
}

const V3_CANDIDATE_BASE = '/assets/candidates/game-ui-v3';
const V3_BOARD_TILE_BASE = '/assets/candidates/board-v3-square/tiles';

const SOURCE_SECTIONS: StaticPreviewSection[] = [
  {
    id: 'style-guides',
    title: 'Style guides',
    description: 'Concept sheets and visual targets used as art direction references. These are not runtime assets.',
    items: [
      {
        id: 'static-states-v1',
        label: 'Static states v1',
        src: '/assets/generated/endless-static-states-v1.png',
        note: 'Cells, buttons, hover/pressed, scroll bands, break/heal.',
      },
      {
        id: 'fx-concept-v1',
        label: 'FX sprite concept v1',
        src: '/assets/generated/endless-fx-sprite-concept-v1.png',
        note: 'Original 8x8 additive FX concept grid.',
        background: 'black',
      },
      {
        id: 'hud-popups-v1',
        label: 'HUD & popups v1',
        src: '/assets/generated/endless-hud-popups-v1.png',
        note: 'Top HUD, hearts, countdown rings, start/retry, mines.',
      },
      {
        id: 'visual-target-v1',
        label: 'Visual target v1',
        src: '/assets/reference/endless-arcade-visual-target-v1.png',
        note: 'Full-screen composition reference.',
      },
    ],
  },
  {
    id: 'production-sheets',
    title: 'Production sheets',
    description: 'Current production sheets and previews generated by the slicing pipeline.',
    items: [
      {
        id: 'ui-panels-v2',
        label: 'UI panels v2',
        src: '/assets/production/ui-panels-production-v2.png',
        note: 'Start, game over, AUTO, break and heal chips.',
      },
      {
        id: 'hud-icons-v2',
        label: 'HUD icons v2',
        src: '/assets/production/hud-icons-production-v2.png',
        note: 'Play, skull, refresh, volume states.',
      },
      {
        id: 'cutouts-v2',
        label: 'Cutouts v2',
        src: '/assets/production/core-cutouts-production-v2.png',
        note: 'Current production source for cutouts.',
        background: 'checker',
      },
      {
        id: 'fx-sprites-v2',
        label: 'FX sprites v2',
        src: '/assets/production/fx-additive-sprites-production-v2.png',
        note: 'Main-flow additive rows.',
        background: 'black',
      },
      {
        id: 'runtime-cutout-preview',
        label: 'Runtime cutout preview',
        src: '/assets/game/preview-cutouts.png',
        note: 'Manifest-driven runtime cutout preview.',
        background: 'checker',
      },
      {
        id: 'runtime-fx-preview',
        label: 'Runtime FX preview',
        src: '/assets/game/preview-fx.png',
        note: 'Manifest-driven runtime FX middle-frame preview.',
        background: 'black',
      },
    ],
  },
  {
    id: 'v3-candidates',
    title: 'v3 candidates',
    description: 'Review-only candidate source sheets. These are intentionally outside the runtime manifest.',
    items: [
      {
        id: 'v3-source',
        label: 'v3 raw style test',
        src: `${V3_CANDIDATE_BASE}/game-asset-style-test-v1-source.png`,
        note: 'Raw style sheet before production slicing.',
        background: 'dark',
      },
      {
        id: 'v3-cutout-alpha',
        label: 'v3 cutout alpha source',
        src: `${V3_CANDIDATE_BASE}/game-asset-style-test-v1-cutout-alpha.png`,
        note: 'Chroma-key test converted to alpha.',
        background: 'checker',
      },
      {
        id: 'v3-fx-black',
        label: 'v3 FX black source',
        src: `${V3_CANDIDATE_BASE}/game-asset-style-test-v1-fx-black.png`,
        note: 'Black-backed additive source before normalized FX production.',
        background: 'black',
      },
      {
        id: 'v3-cutout-preview',
        label: 'v3 cutout preview',
        src: `${V3_CANDIDATE_BASE}/cutouts-preview.png`,
        note: 'Review contact sheet for sliced v3 cutouts.',
        background: 'checker',
      },
      {
        id: 'v3-combo-sheet',
        label: 'v3 combo-burst sheet',
        src: `${V3_CANDIDATE_BASE}/fx/combo-burst-sheet.png`,
        note: 'Temporary transition sheet sliced from vertical concept.',
        background: 'black',
      },
      {
        id: 'board-tiles-numbers-v3-style-aligned',
        label: 'Board tiles & numbers v3 superseded',
        src: '/assets/candidates/board-v3/board-tiles-numbers-v3-style-aligned.png',
        note: 'Superseded review sheet: style direction only; tile silhouettes are too wide for runtime square cells.',
        background: 'checker',
      },
      {
        id: 'board-v3-square-tiles-source',
        label: 'Board v3 square tiles source',
        src: '/assets/candidates/board-v3-square/board-v3-square-tiles-source.png',
        note: 'Current square tile source: normalized into 128x128 review sprites.',
        background: 'checker',
      },
      {
        id: 'board-v3-square-digits-source',
        label: 'Board v3 digit glyph source',
        src: '/assets/candidates/board-v3-square/board-v3-square-digits-source.png',
        note: 'Current digit glyph source: numbers are sliced separately from the tile backgrounds.',
        background: 'checker',
      },
    ],
  },
];

const V3_CANDIDATE_CUTOUTS: StaticPreviewItem[] = [
  { id: 'mine-standard', label: 'Mine standard', src: `${V3_CANDIDATE_BASE}/cutouts/mine-standard.png`, background: 'checker' },
  { id: 'mine-cracked', label: 'Mine cracked', src: `${V3_CANDIDATE_BASE}/cutouts/mine-cracked.png`, background: 'checker' },
  { id: 'flag-standard', label: 'Flag standard', src: `${V3_CANDIDATE_BASE}/cutouts/flag-standard.png`, background: 'checker' },
  { id: 'shield-hint', label: 'Shield hint', src: `${V3_CANDIDATE_BASE}/cutouts/shield-hint.png`, background: 'checker' },
  { id: 'heart-full', label: 'Heart full', src: `${V3_CANDIDATE_BASE}/cutouts/heart-full.png`, background: 'checker' },
  { id: 'heart-empty', label: 'Heart empty', src: `${V3_CANDIDATE_BASE}/cutouts/heart-empty.png`, background: 'checker' },
];

const V3_BOARD_TILE_CANDIDATES: StaticPreviewItem[] = [
  { id: 'preview', label: 'Board v3 square preview', src: `${V3_BOARD_TILE_BASE}/tiles-preview.png`, background: 'checker' },
  { id: 'cell-hidden', label: 'Cell hidden square v3', src: `${V3_BOARD_TILE_BASE}/cell-hidden.png`, background: 'checker' },
  { id: 'cell-revealed', label: 'Cell revealed square v3', src: `${V3_BOARD_TILE_BASE}/cell-revealed.png`, background: 'checker' },
  { id: 'cell-hover', label: 'Cell hover square v3', src: `${V3_BOARD_TILE_BASE}/cell-hover.png`, background: 'checker' },
  { id: 'cell-danger', label: 'Cell danger square v3', src: `${V3_BOARD_TILE_BASE}/cell-danger.png`, background: 'checker' },
  { id: 'cell-pressed', label: 'Cell pressed square v3', src: `${V3_BOARD_TILE_BASE}/cell-pressed.png`, background: 'checker' },
  { id: 'cell-safe', label: 'Cell safe square v3', src: `${V3_BOARD_TILE_BASE}/cell-safe.png`, background: 'checker' },
  { id: 'cell-empty', label: 'Cell empty square v3', src: `${V3_BOARD_TILE_BASE}/cell-empty.png`, background: 'checker' },
  { id: 'cell-disabled', label: 'Cell disabled square v3', src: `${V3_BOARD_TILE_BASE}/cell-disabled.png`, background: 'checker' },
  ...Array.from({ length: 8 }, (_, index): StaticPreviewItem => ({
    id: `num-${index + 1}`,
    label: `Digit ${index + 1} glyph v3`,
    src: `${V3_BOARD_TILE_BASE}/num-${index + 1}.png`,
    background: 'checker',
  })),
];

function buildSections(): AssetSection[] {
  const sprites = getTileSprites();
  if (!sprites) {
    return [];
  }

  const cellItems: AssetItem[] = [
    { id: 'cell-hidden', label: 'Hidden', src: `${RUNTIME_BOARD_TILE_BASE}/cell-hidden.png`, image: sprites.hidden },
    { id: 'cell-revealed', label: 'Revealed', src: `${RUNTIME_BOARD_TILE_BASE}/cell-revealed.png`, image: sprites.revealed },
  ];

  const digitItems: AssetItem[] = sprites.numbers.map((image, index) => ({
    id: `num-${index + 1}`,
    label: `Digit ${index + 1}`,
    src: `${RUNTIME_BOARD_TILE_BASE}/num-${index + 1}.png`,
    image,
  }));

  return [
    {
      id: 'cells',
      title: 'Cell tiles',
      description: 'Board cell surfaces at 128×128. Shown at native resolution on the transparency checker.',
      items: cellItems,
    },
    {
      id: 'digits',
      title: 'Digit glyphs',
      description: 'Runtime v3 digit glyph slices (1-8), drawn over the square revealed tile.',
      items: digitItems,
    },
    {
      id: 'icons',
      title: 'Icons',
      description: 'Mine and flag markers from the tile atlas.',
      items: [
        { id: 'mine', label: 'Mine', src: `${TILE_BASE}/mine.png`, image: sprites.mine },
        { id: 'flag', label: 'Flag', src: `${TILE_BASE}/flag.png`, image: sprites.flag },
      ],
    },
  ];
}

function createStaticPreviewPanel(section: StaticPreviewSection): HTMLElement {
  const panel = document.createElement('section');
  panel.className = 'asset-lab__panel';
  panel.dataset.panelId = section.id;
  panel.append(createPanelHead(section.title, section.description));

  const grid = document.createElement('div');
  grid.className = 'asset-lab__frame-grid asset-lab__frame-grid--wide';

  for (const item of section.items) {
    const cell = document.createElement('article');
    cell.className = 'asset-lab__frame-cell asset-lab__frame-cell--static';
    cell.title = item.src;

    const thumb = document.createElement('div');
    const bgClass =
      item.background === 'black'
        ? ' asset-lab__thumb--black'
        : item.background === 'dark'
          ? ' asset-lab__thumb--dark'
          : ' asset-lab__checker';
    thumb.className = `asset-lab__frame-thumb${bgClass}`;

    const img = document.createElement('img');
    img.src = item.src;
    img.alt = item.label;
    img.loading = 'lazy';
    img.className = 'asset-lab__sprite-img';
    thumb.append(img);

    const meta = document.createElement('div');
    meta.className = 'asset-lab__frame-meta';
    const name = document.createElement('strong');
    name.textContent = item.label;
    const path = document.createElement('code');
    path.textContent = item.src;
    meta.append(name);
    if (item.note) {
      const note = document.createElement('span');
      note.textContent = item.note;
      meta.append(note);
    }
    meta.append(path);

    cell.append(thumb, meta);
    grid.append(cell);
  }

  panel.append(grid);
  return panel;
}

function getContentBBox(image: HTMLImageElement): { w: number; h: number } | null {
  const canvas = document.createElement('canvas');
  canvas.width = image.naturalWidth;
  canvas.height = image.naturalHeight;
  const ctx = canvas.getContext('2d');
  if (!ctx || canvas.width === 0 || canvas.height === 0) return null;

  ctx.drawImage(image, 0, 0);
  const { data, width, height } = ctx.getImageData(0, 0, canvas.width, canvas.height);
  let x0 = width;
  let y0 = height;
  let x1 = 0;
  let y1 = 0;
  let found = false;

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      if (data[(y * width + x) * 4 + 3] > 16) {
        found = true;
        x0 = Math.min(x0, x);
        y0 = Math.min(y0, y);
        x1 = Math.max(x1, x + 1);
        y1 = Math.max(y1, y + 1);
      }
    }
  }

  if (!found) return null;
  return { w: x1 - x0, h: y1 - y0 };
}

function createSpritePanel(section: AssetSection): HTMLElement {
  const panel = document.createElement('section');
  panel.className = 'asset-lab__panel';
  panel.dataset.panelId = section.id;
  panel.append(createPanelHead(section.title, section.description));

  const grid = document.createElement('div');
  grid.className = 'asset-lab__frame-grid';

  section.items.forEach((item, index) => {
    const cell = document.createElement('article');
    cell.className = 'asset-lab__frame-cell asset-lab__frame-cell--static';
    cell.title = item.src;

    const thumb = document.createElement('div');
    thumb.className = 'asset-lab__frame-thumb asset-lab__checker';

    const img = document.createElement('img');
    img.src = item.src;
    img.alt = item.label;
    img.width = item.image.naturalWidth;
    img.height = item.image.naturalHeight;
    img.className = 'asset-lab__sprite-img';
    thumb.append(img);

    const num = document.createElement('span');
    num.className = 'asset-lab__frame-num';
    num.textContent = String(index + 1).padStart(2, '0');
    thumb.append(num);

    const meta = document.createElement('div');
    meta.className = 'asset-lab__frame-meta';

    const name = document.createElement('strong');
    name.textContent = item.label;

    const bb = getContentBBox(item.image);
    const dims = document.createElement('span');
    dims.textContent = bb
      ? `${item.image.naturalWidth}×${item.image.naturalHeight} · content ${bb.w}×${bb.h}`
      : `${item.image.naturalWidth}×${item.image.naturalHeight}`;

    const path = document.createElement('code');
    path.textContent = item.src;

    meta.append(name, dims, path);
    cell.append(thumb, meta);
    grid.append(cell);
  });

  panel.append(grid);
  return panel;
}

const FX_NAV: Array<{ id: EffectPanelId; label: string }> = [
  { id: 'cells', label: 'Cell states' },
  { id: 'board-interactions-v3', label: 'Board interactions v3' },
  { id: 'digits', label: 'Digit particles' },
  { id: 'flag', label: 'Flag wave current' },
  { id: 'flag-place-v3', label: 'Flag place v3' },
  { id: 'wrong-flag-v3', label: 'Wrong flag v3' },
  { id: 'mine', label: 'Mine explosion' },
  { id: 'mine-hit-v3', label: 'Mine hit v3' },
  { id: 'heart-refill-v3', label: 'Heart refill v3' },
];

const FOOTER_NOTES: Record<AssetLabSection, string> = {
  sources: 'Art direction sheets, production sheets, and review-only candidates · not necessarily runtime-loaded',
  sprites: 'Static runtime and candidate cutouts · transparent PNG review before manifest wiring',
  animations: 'Motion previews and FX frame review · canvas-driven behavior lives here',
  'game-ui': 'Runtime UI panels and HUD icons only · source sheets moved to Sources',
  background: 'Environment and backdrop preview · src/ui/ambient-backdrop.ts',
  audio: 'Game SFX & BGM · public/assets/game/audio · gains in game-audio.ts',
};

export function mountAssetGallery(
  root: HTMLElement,
  section: AssetLabSection,
  onNavigate: (path: string) => void,
): () => void {
  root.className = 'app app--asset-lab';
  root.replaceChildren();

  const disposers: Array<() => void> = [];

  if (section === 'sources') {
    const panels = new Map(SOURCE_SECTIONS.map((s) => [s.id, createStaticPreviewPanel(s)]));
    disposers.push(mountLabSection(root, section, onNavigate, SOURCE_SECTIONS.map((s) => ({
      id: s.id,
      label: s.title,
      group: 'sources' as const,
      count: s.items.length,
    })), (id) => panels.get(id)));
    return () => {
      for (const dispose of disposers) dispose();
      root.replaceChildren();
    };
  }

  if (section === 'sprites') {
    const sections = buildSections();
    if (sections.length === 0) {
      const empty = document.createElement('main');
      empty.className = 'asset-lab asset-lab--empty';
      empty.textContent = 'Failed to load tile assets. Check public/assets/tiles.';
      root.append(empty);
      return () => root.replaceChildren();
    }

    disposers.push(mountSpritesSection(root, sections, section, onNavigate));
    return () => {
      for (const dispose of disposers) dispose();
      root.replaceChildren();
    };
  }

  if (section === 'animations') {
    const effects = mountEffectPanels();
    disposers.push(effects.dispose);
    disposers.push(mountLabSection(root, section, onNavigate, FX_NAV.map((fx) => ({
      id: fx.id,
      label: fx.label,
      group: 'animations' as const,
      count: 8,
    })), (id) => effects.panels[id as EffectPanelId]));
    return () => {
      for (const dispose of disposers) dispose();
      root.replaceChildren();
    };
  }

  if (section === 'game-ui') {
    const gameUi = mountGameUiPanels();
    disposers.push(gameUi.dispose);
    disposers.push(mountLabSection(root, section, onNavigate, gameUiNavItems().map((item) => ({
      id: item.id,
      label: item.label,
      group: 'game-ui' as const,
      count: item.count,
    })), (id) => gameUi.panels[id as GameUiLabPanelId]));
    return () => {
      for (const dispose of disposers) dispose();
      root.replaceChildren();
    };
  }

  if (section === 'background') {
    const backdrop = mountBackdropPanels();
    disposers.push(backdrop.dispose);
    disposers.push(mountLabSection(root, section, onNavigate, backdropNavItems().map((item) => ({
      id: item.id,
      label: item.label,
      group: 'background' as const,
      count: item.count,
    })), (id) => backdrop.panels[id as BackdropPanelId]));
    return () => {
      for (const dispose of disposers) dispose();
      root.replaceChildren();
    };
  }

  const audio = mountAudioPanels();
  disposers.push(audio.dispose);
  disposers.push(mountLabSection(root, section, onNavigate, audioNavItems().map((item) => ({
    id: item.id,
    label: item.label,
    group: 'audio' as const,
    count: item.count,
  })), (id) => audio.panels[id as AudioPanelId]));

  return () => {
    for (const dispose of disposers) dispose();
    root.replaceChildren();
  };
}

function mountSpritesSection(
  root: HTMLElement,
  sections: AssetSection[],
  section: AssetLabSection,
  onNavigate: (path: string) => void,
): () => void {
  const shell = document.createElement('div');
  shell.className = 'asset-lab';

  let activeId = sections[0]!.id;
  const spritePanels = new Map(sections.map((s) => [s.id, createSpritePanel(s)]));
  const candidateCutoutSection: StaticPreviewSection = {
    id: 'v3-cutouts',
    title: 'v3 candidate cutouts',
    description: 'Review-only static v3 cutouts. These are not wired into public/assets/game/manifest.json.',
    items: V3_CANDIDATE_CUTOUTS,
  };
  const candidateBoardTileSection: StaticPreviewSection = {
    id: 'board-v3-tiles',
    title: 'Board v3 square slices',
    description: 'Review-only 128x128 square board tiles and standalone digit glyphs. Runtime wiring is still pending.',
    items: V3_BOARD_TILE_CANDIDATES,
  };
  spritePanels.set(candidateCutoutSection.id, createStaticPreviewPanel(candidateCutoutSection));
  spritePanels.set(candidateBoardTileSection.id, createStaticPreviewPanel(candidateBoardTileSection));
  const workspace = createWorkspace();
  const sidebarHost = document.createElement('div');
  sidebarHost.className = 'asset-lab__sidebar-host';
  const panelHost = document.createElement('div');
  panelHost.className = 'asset-lab__panel-host';

  const navItems = (): NavItem[] =>
    [
      ...sections.map((s) => ({
      id: s.id,
      label: s.title.replace(' tiles', '').replace(' glyphs', ''),
      group: 'sprites' as const,
      count: s.items.length,
      })),
      {
        id: candidateCutoutSection.id,
        label: 'v3 Cutouts',
        group: 'sprites' as const,
        count: candidateCutoutSection.items.length,
      },
      {
        id: candidateBoardTileSection.id,
        label: 'Board v3 Tiles',
        group: 'sprites' as const,
        count: candidateBoardTileSection.items.length,
      },
    ];

  function showPanel(id: string): void {
    activeId = id;
    panelHost.replaceChildren();
    const panel = spritePanels.get(id);
    if (panel) panelHost.append(panel);
    renderSidebar();
  }

  function renderSidebar(): void {
    sidebarHost.replaceChildren(createSidebar(navItems(), activeId, showPanel));
  }

  const panel = document.createElement('div');
  panel.className = 'asset-lab__panel-layout';
  panel.append(sidebarHost, workspace);
  workspace.append(panelHost);
  shell.append(createTopbar(section, onNavigate), panel, createFooterNote(FOOTER_NOTES[section]));
  root.append(shell);
  showPanel(activeId);

  return () => undefined;
}

function mountLabSection(
  root: HTMLElement,
  section: AssetLabSection,
  onNavigate: (path: string) => void,
  items: NavItem[],
  getPanel: (id: string) => HTMLElement | undefined,
): () => void {
  const shell = document.createElement('div');
  shell.className = 'asset-lab';

  let activeId = items[0]?.id ?? '';
  const workspace = createWorkspace();
  const sidebarHost = document.createElement('div');
  sidebarHost.className = 'asset-lab__sidebar-host';
  const panelHost = document.createElement('div');
  panelHost.className = 'asset-lab__panel-host';

  function showPanel(id: string): void {
    activeId = id;
    panelHost.replaceChildren();
    const panel = getPanel(id);
    if (panel) panelHost.append(panel);
    renderSidebar();
  }

  function renderSidebar(): void {
    sidebarHost.replaceChildren(createSidebar(items, activeId, showPanel));
  }

  const panel = document.createElement('div');
  panel.className = 'asset-lab__panel-layout';
  panel.append(sidebarHost, workspace);
  workspace.append(panelHost);
  shell.append(createTopbar(section, onNavigate), panel, createFooterNote(FOOTER_NOTES[section]));
  root.append(shell);
  if (activeId) showPanel(activeId);

  return () => undefined;
}
