import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { collectBootAssets } from '../game-client/ui/boot/asset-registry.ts'
import type { GameAssetManifestSnapshot } from '../game-client/ui/boot/types.ts'
import { BRAND_LOGO_PATH, BRAND_MARK_PATH, BRAND_SLUG, brandLogPrefix, brandServiceWorkerCacheName } from '../lib/brand.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const publicDir = join(root, 'public')
const manifestPath = join(publicDir, 'assets/game/manifest.json')
const outputPath = join(publicDir, 'sw.js')

const packageJson = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as { version?: string }
const cacheVersion = packageJson.version ?? '0'

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as GameAssetManifestSnapshot
const bootAssets = collectBootAssets(manifest)

let webpMap: Record<string, string> = {}
try {
  webpMap = JSON.parse(readFileSync(join(publicDir, 'assets/boot-webp-map.json'), 'utf8')) as Record<string, string>
} catch {
  // WebP map is optional before first optimize step.
}

const precache = new Set<string>([
  BRAND_MARK_PATH,
  BRAND_LOGO_PATH,
  '/assets/boot-weights.json',
  '/assets/boot-webp-map.json',
  '/assets/game/manifest.json',
  ...bootAssets.map((asset) => asset.url),
  ...Object.values(webpMap),
])

const precacheList = [...precache].sort()

const cacheName = brandServiceWorkerCacheName(cacheVersion)

const swSource = `/* Generated by scripts/gen-service-worker.ts — do not edit */
const CACHE_NAME = '${cacheName}';
const PRECACHE_URLS = ${JSON.stringify(precacheList, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith('${BRAND_SLUG}-') && key !== CACHE_NAME)
          .map((key) => caches.delete(key)),
      ),
    ).then(() => self.clients.claim()),
  );
});

function canCacheResponse(request, response) {
  if (request.headers.get('range')) return false;
  return response.ok && response.status === 200 && response.type === 'basic';
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) return cached;

  const response = await fetch(request);
  if (canCacheResponse(request, response)) {
    void cache.put(request, response.clone());
  }
  return response;
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    if (canCacheResponse(request, response)) {
      void cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await cache.match(request);
    if (cached) return cached;
    throw new Error('Offline and no cached response');
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
  }
});
`

writeFileSync(outputPath, swSource)
console.log(`${brandLogPrefix('service-worker')}: ${precacheList.length} precache urls → public/sw.js (cache ${cacheName})`)
